spring:
  application:
    name: UberChallenge
  datasource:
    username: admin
    password: 123456
    url: jdbc:postgresql://127.0.0.1:5430/uber_challenge?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: RestDB-Pool
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

server:
  port: 8082

logging:
  level:
    org:
      hibernate:
        SQL: TRACE

app:
  pagination:
    default-page-size: 10
    default-page: 0

jwt:
  secret: mySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong12345678
  expiration: 86400000

ml:
  service:
    url: http://localhost:5000
