# -*- coding: utf-8 -*-
"""KVAS_UseModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxkXtrurAsqLNIah6nHAqM9CwLYHjhrv
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import catboost as catboost


from catboost import CatBoostRegressor

df_test = pd.read_csv("test_dataframe.csv")

modelDist = CatBoostRegressor()
modelDist.load_model("catboost_model_dist.cbm")

ypred = modelDist.predict(df_test)

ypred = pd.DataFrame({"distance":ypred})

ypred.to_csv("test_ans.csv", index=False)